</$objtype/mkfile

<../config

all:V:	grabit

install safeinstall:V:	$POSTBIN/grabit $POSTLIB/grabit.ps

installall safeinstallall:V:	install

$POSTBIN/grabit:	grabit
	cp $prereq $target

$POSTLIB/grabit.ps:	grabit.ps
	cp $prereq $target

grabit:	grabit.rc
	sed 's?^POSTLIB=.*?POSTLIB='$POSTLIB'?' grabit.rc >grabit
	chmod 775 grabit

clean nuke:V:
	rm -f grabit
