</$objtype/mkfile

<../config

TMACDIR=/sys/lib/tmac

all:V:	tmac.pictures

install safeinstall:V:	$TMACDIR/tmac.pictures

installall safeinstallall:V: install

clean nuke:V:
	rm -f tmac.pictures

$TMACDIR/tmac.pictures:	tmac.pictures
	cp $prereq $target

tmac.pictures : pictures.sr
	cp $prereq $target
